version: 2

checkout:
  post:
    - >
      if [ -n "$CI_PULL_REQUEST" ]; then
        PR_ID=${CI_PULL_REQUEST##*/}
        git fetch origin +refs/pull/$PR_ID/merge:
        git checkout -qf FETCH_HEAD
      fi

jobs:

  unittests:
    docker:
      - image: circleci/python:2.7.15-stretch
    steps:
      - checkout
    steps:
      - checkout
      - run: last

  wagon:
    docker:
      - image: amd64/centos:centos7.3.1611
    steps:
      - checkout
      - run: last

  cloudify-manager:
    docker:
      - image: amd64/centos:centos7.3.1611
    steps:
      - checkout
      - run: last

workflows:
  version: 2
  tests:
    jobs:
      - unittests
      - wagon
      - cloudify-manager
