tosca_definitions_version: cloudify_dsl_1_3

imports:
  - http://www.getcloudify.org/spec/cloudify/4.3.2/types.yaml
  - plugin:cloudify-awssdk-plugin

inputs:

  aws_access_key_id:
    type: string
    default: { get_secret: aws_access_key_id }

  aws_secret_access_key:
    type: string
    default: { get_secret: aws_secret_access_key }

  aws_region_name:
    type: string
    default: { get_secret: ec2_region_name }

dsl_definitions:

  client_config: &client_config
    aws_access_key_id: { get_input: aws_access_key_id }
    aws_secret_access_key: { get_input: aws_secret_access_key }
    region_name: { get_input: aws_region_name }

  aws_config: &aws_config
    aws_access_key_id: { get_input: aws_access_key_id }
    aws_secret_access_key: { get_input: aws_secret_access_key }
    ec2_region_name: { get_input: aws_region_name }

node_templates:

  wordpress_example:
    type: cloudify.nodes.aws.CloudFormation.Stack
    properties:
      resource_config:
        kwargs:
          StackName: WordpressExample
          Parameters:
          - ParameterKey: KeyName
            ParameterValue: example
          - ParameterKey: DBPassword
            ParameterValue: zadkckdoekd
          - ParameterKey: DBUser
            ParameterValue: example
          - ParameterKey: DBRootPassword
            ParameterValue: zadkckdoekd
          TemplateURL: https://s3.eu-central-1.amazonaws.com/cloudformation-templates-eu-central-1/WordPress_Single_Instance.template
      client_config: *client_config

  HelloBucket:
    type: cloudify.nodes.aws.CloudFormation.Stack
    properties:
      resource_config:
        kwargs:
          StackName: HelloBucket
          TemplateBody:
            AWSTemplateFormatVersion: "2010-09-09"
            Description: S3 HelloBucket
            Resources:
              HelloBucket:
                Type: AWS::S3::Bucket
                Properties:
                  AccessControl: PublicRead
                  WebsiteConfiguration:
                    IndexDocument: index.html
                    ErrorDocument: error.html
      client_config: *client_config
